### ISSUE TITLE
SCORM Profile IRI changed

### ISSUE THREAD

**Issue by creighton** [adlnet/Starting-from-SCORM-A-Developers-Guide#3]
The iris in the SCORM Profile changed to https://w3id.org/xapi/scorm. This will impact the context activity iri, and the 4 document iris (activity state, attempt state, activity profile and agent profile), along with the suspend_data iri.

https://github.com/adlnet/xAPI-SCORM-Profile/issues/36

**Comment by creighton** [comment]
https://github.com/adlnet/Starting-from-SCORM-A-Developers-Guide/blob/master/Resources/SCORMToXAPIFunctions.js#L112

**Comment by jono-poltrack** [comment]
The profile IDs have been updated (as well as the IRIs to identify state/profile data).
