### ISSUE TITLE
Add comments where code is to be placed

### ISSUE THREAD

**Issue by jono-poltrack** [adlnet/Starting-from-SCORM-A-Developers-Guide#5]
In the original Roses content and every zip file (corresponding to steps) include a comment where the pasted code will go to avoid confusion.

**Comment by rneatrour** [comment]
It seems like a bad idea to version control a zip file. Does there need to be five zip files of the same thing? It doesn't seem like a good idea. If it is necessary, should the first zip have all the changes added and commented out, and subsequent zip files have the the code uncommented out pertaining to that step?

**Comment by jono-poltrack** [comment]
Might be bad to version control zip file.  True.  intent here is that we have steps along the way so people can automatically catch up if they fall behind.  Open to whatever works if not versioning zips.

**Comment by jono-poltrack** [comment]
oh... forgot to mention.. that the source for those files (well.. the first and last step I think at least) -- is at https://github.com/adlnet/SCORM-to-TLA-Roadmap/tree/master/examples/RosesCourseConversion

**Comment by rneatrour** [comment]
I added the commented out code to the original, and I removed zip files 2 through 4. I changed the extra credit zip file to  RosesFinal. It contains the completed code. This seemed to be the best approach.

**Comment by ljwolford** [comment]
fixed by #6
